# Generated by Django 3.2.6 on 2021-08-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(blank=True, max_length=200, null=True)),
                ('ar_title', models.CharField(blank=True, max_length=200, null=True)),
                ('en_description', models.CharField(blank=True, max_length=200, null=True)),
                ('ar_description', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('cat_image', models.ImageField(blank=True, upload_to='catalog/categories')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
