# Generated by Django 3.2.6 on 2021-08-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ar_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Arabic Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ar_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Arabic title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='en_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='English Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='en_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='English title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
