# Generated by Django 3.2.6 on 2021-08-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210826_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='English title')),
                ('ar_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Arabic title')),
                ('en_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='English Description')),
                ('ar_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Arabic Description')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('cat_image', models.ImageField(blank=True, upload_to='catalog/brands')),
                ('lang_type', models.IntegerField(default=0, verbose_name='0 english, 1 arabic')),
            ],
            options={
                'db_table': 'brands',
            },
        ),
    ]
