# Generated by Django 3.2.6 on 2021-08-26 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='English title')),
                ('ar_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Arabic title')),
                ('en_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='English Description')),
                ('ar_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Arabic Description')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('thumb_img', models.ImageField(blank=True, upload_to='catalog/prod_thumbs', verbose_name='Thumbnail Image')),
                ('product_status', models.BooleanField(blank=True, default=1, verbose_name='Is Active')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=20.0, max_digits=10, null=True, verbose_name='Cost Price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=40.0, max_digits=10, null=True, verbose_name='Retail Price')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.RemoveField(
            model_name='brand',
            name='lang_type',
        ),
        migrations.AddField(
            model_name='brand',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'X Large')], max_length=50, null=True, verbose_name='Size')),
                ('stock', models.IntegerField(blank=True, default=10, null=True, verbose_name='Stock')),
                ('child_sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='catalog.product')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='catalog/prod_images', verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalog.product')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category'),
        ),
    ]
