# Generated by Django 3.2.6 on 2021-08-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210826_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='ar_description',
            field=models.CharField(blank=True, default='وصف الكاتجوري بالعربي', max_length=200, null=True, verbose_name='Arabic Description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='ar_title',
            field=models.CharField(blank=True, default='أسم الكاتجوري بالعربي', max_length=200, null=True, verbose_name='Arabic title'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_description',
            field=models.CharField(blank=True, default='Brand Description', max_length=200, null=True, verbose_name='English Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ar_description',
            field=models.CharField(blank=True, default='وصف الكاتجوري بالعربي', max_length=200, null=True, verbose_name='Arabic Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ar_title',
            field=models.CharField(blank=True, default='أسم البراند بالعربي', max_length=200, null=True, verbose_name='Areabic title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='en_description',
            field=models.CharField(blank=True, default='Category English Description', max_length=200, null=True, verbose_name='English Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ar_description',
            field=models.CharField(blank=True, default='وصف المنتج بالعربي', max_length=200, null=True, verbose_name='Arabic Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ar_title',
            field=models.CharField(blank=True, default='أسم المنتج بالعربي', max_length=200, null=True, verbose_name='Arabic title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='en_description',
            field=models.CharField(blank=True, default='Product Description', max_length=200, null=True, verbose_name='English Description'),
        ),
    ]
